repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/tr8team/gotrade-pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: yamlfmt
      - id: mdfmt
        exclude: ^.*Changelog\.(MD|md)$
      - id: nixfmt
      - id: shfmt
      - id: jsonfmt
  - repo: local
    hooks:
      - id: gitlint-linter
        name: Lints Gitlint to conform to atomi_release.yaml
        entry: sg gitlint
        files: (atomi_release.yaml|.gitlint)
        language: system
        pass_filenames: false

      - id: exec-scripts
        name: Configure Scripts
        entry: chmod +x
        files: ^.*\.sh$
        pass_filenames: true
        language: system
